name: POI PR

on:
  pull_request:
    branches: 
    - main
    paths:
    - 'apis/poi/**'
    - '.github/workflows/poi-pr.yml'
    types: [edited, synchronize, opened, reopened]

env:
  APPLICATIONPATH: apis/poi/
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Switch directory
      run: pushd ${{ env.APPLICATIONPATH }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test tests/UnitTests/UnitTests.csproj --no-build --verbosity normal
    - name: Switch directory
      run: popd
